### ISSUE TITLE
Self-contained example?

### ISSUE THREAD

**Issue by bard** [jcubic/lips#123]
I'm experimenting with this project and I'm finding it difficult to go beyond a "hello world".

For example, I'm trying to construct a literal JavaScript object to pass it as argument to `fetch`. I see in the repository that there is a `make-object` macro, however just calling results in "Unbound variable"; there are examples that use it, such as https://github.com/jcubic/lips/blob/7403fcd6265ac6082e2645245128f35f1e41968f/examples/app.html, and I tried to `load` the same files that example does (`bootstrap.scm` etc), but that did not make `make-object` available. Other examples refer to `helpers.lips`, but I cannot find that anywhere. And I'm not sure whether I'm using the scm/lips extensions correctly. In short, it's all a bit confusing. :)

I understand the project is undergoing a major version change, and maybe old code is mixed with new. Is there a simple, self-contained example that goes through the basics? For reference, this is what I've been experimenting with:

index.html:

```html
<!DOCTYPE html>
<html>
  <head>
    <script
      type="text/javascript"
      src="https://unpkg.com/@jcubic/lips"
    ></script>
    <script type="text/x-lips" src="index.lips"></script>
  </head>
  <body>
  </body>
</html>
```

index.lips:

```scheme
;; -*- scheme -*-

(define fetch-options (make-object))

(let ((response (window.fetch "/index.html")))
  (console.log (response.text)))
```

**Comment by jcubic** [comment]
You're using two different types of the project. The code you're using is 1.0 Beta but you're using old version 0.20.2 from npm.

I need to properly document this, because it's confusing. The readme example have Beta version.

`console.log` syntax is only available in beta. For standard version on NPM that is really really old is `(. console 'log)` or `(.. console.log)`.

If you want to use this project fully you should use: ling https://unpkg.com/@jcubic/lips@beta

Also not that if you want to have all standard functions and macros you need to boostrap with Scheme files. Run this code:

```scheme
(load "https://unpkg.com/@jcubic/lips@beta/dist/std.scm" lips.env.__parent__)
```

It will fetch the standard library and load is as global environment. I'm working on embeding the Scheme code into one bundle, maybe when 1.0 will be ready You only will need one JS file.

**Comment by bard** [comment]
Thanks for your help. I think part of the confusion could be cleared by either removing instructions on how to import the 0.20.2 version, so that the whole README is about just the beta, or by specifying to which version the usage instructions refer to.

I must still be missing something though, because the following prints the greeting but then errors out with `Unbound variable: make-object`.

```html
<!DOCTYPE html>
<html>
  <head>
    <script type="text/javascript" src="https://unpkg.com/@jcubic/lips@beta"></script>
    <script type="text/x-scheme" bootstrap>
      (load "https://unpkg.com/@jcubic/lips@beta/dist/std.scm" lips.env.__parent__)
      (console.log "hello, world")
      (define foo (make-object))
    </script>
  </head>
  <body></body>
</html>
```

**Comment by jcubic** [comment]
Yes, there was breaking change in beta make-object was renamed to `object`. Sorry didn't mention that in first comment. So you code should be:

```scheme
(define fetch-options (object))

(let ((response (window.fetch "/index.html")))
  (console.log (response.text)))
```

You can see that this works by copy pasting into https://lips.js.org/beta.html I also need to update the website I still work on new one.

**Comment by jcubic** [comment]
You can also use:

```scheme
(define fetch-options &())
```

`&(:foo 10)` is shortcut to object literals that work the same as vectors `#()` so the thing inside is automatically quoted.

**Comment by jcubic** [comment]
Also the bootstrap argument is shortcut for the load you have, so if you use `bootstrap` you don't need the use load with std.scm. That argument was attempt of making the bootstrapping simpler. I hope I will be able to bundle the scheme code with JS file. I was working on prototype of rollup plugin, it kind of worked.

**Comment by jcubic** [comment]
Updated README to include installation instructions only for beta. The old README is on [LIPS NPM home page](https://www.npmjs.com/package/@jcubic/lips).

**Comment by bard** [comment]
Thank you! I understand a little better now. Eager to see where this project is going, it looks like great fun!

Here's what I ended up with, in case it might help others. 

index.html:

```html
<!DOCTYPE html>
<html>
  <head>
    <script
      type="text/javascript"
      src="https://unpkg.com/@jcubic/lips@beta"
    ></script>
  </head>
  <body>
    <script type="text/x-scheme" src="index.scm" bootstrap></script>
  </body>
</html>
```

index.scm:

```scheme
;; -*- scheme -*- 

(let ((response (fetch "/" (object :headers (object :accept "text/html")))))
  (console.log (response.text)))
```

**Comment by jcubic** [comment]
You don't need this line:
```
;; -*- scheme -*- 
```
it was added for emacs to mark lips file extension as Scheme, the new approach is to use scm file extension that is already handled by Emacs as Scheme.

**Comment by jcubic** [comment]
Just for reference here is base AJAX and DOM example https://codepen.io/jcubic/pen/vYyPQgy
