### ISSUE TITLE
Potential error in lips.js

### ISSUE THREAD

**Issue by wkechel** [jcubic/lips#158]
I detected the following code snippet (lips.js:4405):

    LString.prototype.cmp = function(string) {
        typecheck('LStrign::cmp', string, 'string');
        var a = this.valueOf();
        var b = string.valueOf();
        if (a < b) {
            return -1;
        } else if (a === b) {
            return 0;
        } else {
            return 1;
        }
    };

I think it should be: typecheck('LString::cmp', string, 'string');
I know it is only the error message, though.

**Comment by jcubic** [comment]
Oh, thanks, will fix this.
