### ISSUE TITLE
try..catch is broken

### ISSUE THREAD

**Issue by jcubic** [jcubic/lips#163]
Here is an example:

```scheme
(define (until-zero fn lst)
  (try (for-each (lambda (x)
                   (if (zero? x)
                       (throw 'ZONK)
                       (fn x)))
                 lst)
       (catch (e)
              (print "err")
              (print e))))

(print "----")
(until-zero print '(1 2 0 3 4))
(print "----")
(until-zero print '(0 1 2 3 4))
```
it prints:
```
----
1
2
err
ZONK
3
4
----
err
ZONK
1
2
3
4
```

another issue is that when throws is called it keep adding Error:
so last error is:
```
Error: Error: Error: Error: ZONK
```

**Comment by jcubic** [comment]
This is a fundametal error, exceptions don't stop the execution:

```scheme
(try
 (begin
   (print 'foo)
   (print 'bar)
   (throw 'ZONK)
   (print 'baz)
   (print 'quux))
 (catch (e)
        (print e)))
```

Probably because if real exceptions happen it's bubble up in `evaluate`. Maybe `silent.error` needs to be introduced like in **R shiny** framework. Or we need to wait for continations.

**Comment by jcubic** [comment]
Another idea is to create stack of error handlers and handle errors by hand instead of using functions.

**Comment by lassik** [comment]
Does Lips implement `(guard ...)` from R7RS?

**Comment by jcubic** [comment]
@lassik No, but I probably can just be implemented it with `try..catch`, it will be simple symbol swapping.
I think that this is a good time to start adding continuations.

**Comment by jcubic** [comment]
Basic code works:

```scheme
(try
 (begin
   (print 'foo)
   (print 'bar)
   (throw 'ZONK)
   (print 'baz)
   (print 'quux))
 (catch (e)
        (print e)))
```

But the for-each example is still not fixed.
