### ISSUE TITLE
Use Grammarly to correct grammar and spell mistakes in docstrings

### ISSUE THREAD

**Issue by jcubic** [jcubic/lips#195]
I've copied two functions in the other issue, and [Grammarly](https://www.grammarly.com/) found quite a few issues. It would be nice to use it for all docstrings.

- [x] Corect lib/bootstrap.scm
- [x] Correct lib/R5RS.scm
- [x] Correct lib/R7RS.scm
- [x] Correct embedded docstrig in src/lips.js, also fix indentation

**Comment by lalit-03** [comment]
Hey @jcubic, I would like to work on this issue as part of Hacktoberfest. Can you assign it to me?

**Comment by jcubic** [comment]
@lalit-03 You can take this task, but you probably will not fix everything at once so I would rather not assign the task to you. Actually, I don't use assignments in this project, I never use them on GitHub.

**Comment by jcubic** [comment]
I think that most the work was done thanks to Hacktoberfest contributors.
