### ISSUE TITLE
command-line and SRFI 193 return values

### ISSUE THREAD

**Issue by lassik** [jcubic/lips#196]
Based on commit 9ccdce3:

* `command-line` should return `("")` when not running a script. R7RS specifies that the return value must be a list with at least one string; SRFI 193 specifies that the return value must be exactly `("")`. The SRFI 193 convention comes from Chez Scheme.

From [`193.scm`](https://github.com/jcubic/lips/blob/aa0279c014120492506a5038a8708dbbefb333a8/lib/srfi/193.scm):

* `script-file` and `script-directory` should return `#f` when not running a script.

**Comment by jcubic** [comment]
Oh, thanks for the information. Will update the function to return `("")`.

**Comment by lassik** [comment]
Thanks for the fast fix!

`(command-args)` should return `()` when there is no command.

**Comment by lassik** [comment]
Re: coding style, schemers often use `(and foo bar)` instead of `(if foo bar #f)`.

**Comment by jcubic** [comment]
fixes the issue and refactored to have `(and foo bar)`. Thanks for your suggestions.
