### ISSUE TITLE
`(inexact->exact 0)` errors

### ISSUE THREAD

**Issue by WarpedWartWars** [jcubic/lips#199]
```scheme
lips> (inexact->exact 0)
symbol #:value is not a function
Call (stack-trace) to see the stack
Thrown exception is in global exception variable,
use (display exception.stack) to display JS stack trace
```

**Comment by jcubic** [comment]
Thanks for the report, it seems that `inexact->exact` don't work on exact numbers the same is for any exact number like `10` or `1/2`.

Also, this error message should be improved, `symbol #:value is not a function` it happens if you use `(--> object (fn x))` and object doesn't have `fn` method.

**Comment by jcubic** [comment]
The problem was that `inexact->exact` tested if the value is `real?` or complex manually instead of using `exact?` procedure.

**Comment by WarpedWartWars** [comment]
I honestly had *no idea* what `symbol #:value is not a function` meant.

When do you expect https://lips.js.org to update? GitHub Pages links there, but...

**Comment by jcubic** [comment]
> I honestly had no idea what symbol #:value is not a function meant.

this is an error in `-->` macro it was trying to execute `(--> n (toRatioalize))` but only LFloat and LComplex had this method so it was throwing an error. The code was old now I would do `(n.toRatioalize)` that throw a better-looking error. I will create an issue to make the error message better.

> When do you expect https://lips.js.org to update? GitHub Pages links there, but...

It may take a while I usually, do a lot of changes before I release a new beta version, but I think I have enough to create a new version. Maybe just fix the error message first.

**Comment by jcubic** [comment]
Just released a new beta version.

**Comment by WarpedWartWars** [comment]
Uh...
![Screenshot (219)](https://user-images.githubusercontent.com/91039320/141849020-dd34ee30-a247-491d-96a4-a833a740ccff.png)

**Comment by jcubic** [comment]
It's coveralls. Not sure why but code coverage dropped by -0.03%. I probably added something i JS that is not tested. The important part is Travis and that tests passes.

**Comment by WarpedWartWars** [comment]
> Just released a new beta version.

On https://lips.js.org?

**Comment by jcubic** [comment]
This is something with CDN it can't fetch new standard library file. It works in bookmarklet because it always gets the latest file (it use the latest commit hash).

**Comment by jcubic** [comment]
It works now.

**Comment by WarpedWartWars** [comment]
> It works now.

```scheme
lips> (exact 0)
0
```
It does!

**Comment by WarpedWartWars** [comment]
But now:

```scheme
lips> (exact (sqrt -2))
+1.4142135623730951i
```
when I think it should be
```scheme
lips> (exact (sqrt -2))
+13414093155/9485196233i
```

**Comment by jcubic** [comment]
There is task #34 to add unit tests for the whole numerical tower, there are still no tests for `inexact->exact` that's why there can be bugs.

```scheme
lips> (exact 0.1+0.1i)
1/10+1/10i
lips> (exact +0.1i)
+0.1i
```

Probably the problem is that the code only check if `re` part is exact:

```scheme
lips> (real-part +0.1i)
0
lips> (exact 10+0.1i)
10+0.1i
```

**Comment by WarpedWartWars** [comment]
Ah.

> For now you can fix this by adding `0.0` to complex number:

Thanks for the workaround!

**Comment by WarpedWartWars** [comment]
Now this works:
```scheme
lips> (define-macro (for iterator start end . body)
          `(let loop ((,iterator ,start))
             (if (<= ,iterator ,end)
                 (loop (+ ,iterator 1) (begin ,@body)))))
lips> (for j -2 2
           (for k -2 2
                (let ((sqrtj+ki (exact (+ 0.0 (sqrt (+ j (* k +1i)))))))
                  (display (join "" (list "(sqrt " (+ j (* k +1i)) ") ")))
                  (if (= (square sqrtj+ki) (+ j (* k +1i)))
                      (display "=")
                      (display "≈"))
                  (display " ")
                  (display sqrtj+ki)
                  (newline))))
(sqrt -2-2i) ≈ 5764590441/8956870598-119170264/76697297i
(sqrt -2-1i) ≈ 2213931997/6444077210-1475816163/1014065014i
(sqrt -2) ≈ +13414093155/9485196233i
(sqrt -2+1i) ≈ 2213931997/6444077210+737908081/507032507i
(sqrt -2+2i) ≈ 5764590441/8956870598+2621745807/1687340534i
(sqrt -1-2i) ≈ 614307419/781411108-11424204247/8981153908i
(sqrt -1-1i) ≈ 3922824693/8619890341-160859975/146411487i
(sqrt -1) = +1i
(sqrt -1+1i) ≈ 3922824693/8619890341+482579924/439234461i
(sqrt -1+2i) ≈ 614307419/781411108+5712102123/4490576954i
(sqrt -2i) = 1-1i
(sqrt -1i) ≈ 728883234/1030796555-6707046578/9485196233i
(sqrt 0) = 0
(sqrt +1i) ≈ 728883234/1030796555+6707046577/9485196233i
(sqrt +2i) = 1+1i
(sqrt 1-2i) ≈ 5712102123/4490576954-1228614839/1562822216i
(sqrt 1-1i) ≈ 482579924/439234461-3922824694/8619890341i
(sqrt 1) = 1
(sqrt 1+1i) ≈ 482579924/439234461+3922824693/8619890341i
(sqrt 1+2i) ≈ 5712102123/4490576954+614307419/781411108i
(sqrt 2-2i) ≈ 2621745807/1687340534-221715017/344495023i
(sqrt 2-1i) ≈ 737908081/507032507-1106965999/3222038605i
(sqrt 2) ≈ 13414093155/9485196233
(sqrt 2+1i) ≈ 737908081/507032507+2213931997/6444077210i
(sqrt 2+2i) ≈ 2621745807/1687340534+5764590441/8956870598i
```

**Comment by WarpedWartWars** [comment]
Now what is this?
```scheme
lips> (/ 3+6i 2+4i)
Cannot read property 'op' of undefined
Call (stack-trace) to see the stack
Thrown exception is in global exception variable,
use (display exception.stack) to display JS stack trace
```

**Comment by jcubic** [comment]
I think that I have incomplete unit tests for `/`, it seems that one is missing.

**Comment by jcubic** [comment]
The problem was this code:

```javascript
    const [ a, b ] = this.coerce(n);
    const denom = b.factor();
    const num = a.mul(b.conjugate());
    const re = num.__re__.op('/', denom);  // num was not complex
    const im = num.__im__.op('/', denom);
    return LComplex({ re, im });
```

I've also found another two bugs:
```scheme
lips> (/ 0.1+0.1i 0.1+0.1i)
1.0000000000000002+0.0i         ;; it should return 1.0
lips> (* 0.1+0.1i 0.1-0.1i)
0.020000000000000004+0.0i       ;; it should return float number
```

Now there is a special case where numbers are the same, the result is always 1 or 1.0 depending on the type of the arguments.

It may take a while before the new beta version will be published. But if you want to play with online REPL you can use CodePen demo that uses the devel version. https://codepen.io/jcubic/full/GxgWBq

**Comment by WarpedWartWars** [comment]
> https://codepen.io/jcubic/full/GxgWBq

Thanks!
```scheme
lips> (/ 2+4i 3+6i)
2/3
lips> (/ 3+6i 2+4i)
3/2
lips> (/ 4+6i 2+4i)
8/5-1/5i
```
