### ISSUE TITLE
Various typos

### ISSUE THREAD

**Issue by WarpedWartWars** [jcubic/lips#202]
For example:
* the help for `*` has "Multiplicate" instead of "Multiply"
* at least two functions have "Function return" instead of "This function returns" or something
etc.
I'm thinking of making a pull request with all of these fixed, but I don't know where they all are.

Edit: they're in lips.js.

**Comment by jcubic** [comment]
Yes, there are a lot of errors. I'm not a native English speaker and make a lot of mistakes. There is an issue to run Grammarly over every docstrigs #195. Some of them are in src/lips.js and some of them in lib/*.scm files.

**Comment by jcubic** [comment]
Also, I recently removed the UMD code from src/lips.js so the indentation of the whole code changed and all docstrings have the wrong indent, which also needs to be fixed.

**Comment by WarpedWartWars** [comment]
Ok. I've made a pull request [here](https://github.com/jcubic/lips/pull/204) to fix them. However, it's a draft pull request because I haven't made all of the fixes yet.

**Comment by jcubic** [comment]
Marking this as duplicate because there is a new issue that also explains how to contribute for newcomers.
