### ISSUE TITLE
Review doc strings and fix spelling and grammar mistakes

### ISSUE THREAD

**Issue by jcubic** [jcubic/lips#217]
Check the JavaScript source file [src/lips.js](https://github.com/jcubic/lips/blob/devel/src/lips.js) and [all Scheme files](https://github.com/jcubic/lips/tree/devel/lib) (in the lib directory) and fix any spelling and grammar errors.

This is [a similar PR](https://github.com/jcubic/lips/pull/204) that fixes some of the errors in doc strings.

Remember to create PR to the devel branch.

**Comment by MridulTailor** [comment]
I would like to work on this as part of hacktoberfest.

**Comment by jcubic** [comment]
@MridulTailor great go for it

**Comment by SachXD** [comment]
can i also work as a part of hacktoberfest '22 on this?

**Comment by jcubic** [comment]
Great take a look at #195, it's the same but suggest using Grammarly on those strings, it can help in fixing grammar and spelling mistakes.

**Comment by MridulTailor** [comment]
can you add hacktoberfest label to this discussion or issue please?

**Comment by Siddharthqr** [comment]
I would also like to work on this as a part of hacktoberfest.

**Comment by jcubic** [comment]
I think that src/lips.js is done. but I will be unavailable for whole first week of October. Will get back to this when I'll get back home. I need to organize it better. Too many people want to do the same thing.

I will create an issue for each scheme file in lib directory and there will be one person assigned per task. I usually don't do this on GitHub, but October is a month we're you can get a lot of contributions at once.

If you still want to contribute you need to wait when I'm back.

**Comment by SachXD** [comment]
@jcubic i actually fixed a lot of typos for each scheme file in lib directory also check PR btw :smile:

**Comment by jcubic** [comment]
Thanks, will check when I get back from my vacation.

**Comment by MridulTailor** [comment]
> can you add hacktoberfest label to this discussion or issue please?

can you add another label 'hacktoberfest-accepted' please?

**Comment by jcubic** [comment]
From what I know you need topic on repo or this label you don't need both especially on issues.
