### ISSUE TITLE
`odd?` and `even?` results on non-integers

### ISSUE THREAD

**Issue by jpellegrini** [jcubic/lips#242]
Hello!

I noticed LIPS returns these:

```scheme
(odd? 1.5)    => #f
(odd? 1/2)    => undefined
(odd? 0+1i)   => undefined
(odd? 0+1.0i) => undefined

(even? 1.5)    => #t
(even? 1/2)    => #t
(even? 0+1i)   => #t
(even? 0+1.0i) => #t
```

I suppose this is because `even?` is implemented as the negation of `odd?`? Which I find strange, because

```scheme
(define x (odd? `1/2))
(list x)                            => (#<undefined>)
(not x)                             => #f  ;; ???
```

Anyway, I suppose they should all be either false or error... (the standards don't say much about this)

**Comment by jcubic** [comment]
Thanks for the report. Yes `odd?` and `even?` should return an error on noninteger.

This is the code:
```javascript
LNumber.prototype.isOdd = function() {
    if (LNumber.isNative(this.__value__)) {
        if (this.isBigNumber()) {
            return this.__value__ % BigInt(2) === BigInt(1);
        }
        return this.__value__ % 2 === 1;
    } else if (LNumber.isBN(this.__value__)) {
        return this.__value__.isOdd();
    }
};
// -------------------------------------------------------------------------
LNumber.prototype.isEven = function() {
    return !this.isOdd();
};
```

float number is native so `odd?` always return false. The other cases are not handled so it returns `undefined` and in JavaScript `!undefined` is `true`. this method is inherited by all number types.
