### ISSUE TITLE
(question) how to do default parameters

### ISSUE THREAD

**Issue by dragoncoder047** [jcubic/lips#249]
```scheme
lips> (define (foo b (x 1) (y 2)) (display (list b x y)))
lips> (foo 1)
Error: Unbound variable `x'
lips>
```

how do I make a function with default parameters?

I saw s7 scheme has a `define*` macro that make lambdas that allow default parameters (as well as keyword arguments) -- [ref](https://ccrma.stanford.edu/software/snd/snd/s7.html#define*), but I could not find any kind of RnRS standard describing a facility for optional parameters in scheme. Will LIPS ever support optional arguments/parameters with defaults?

**Comment by jcubic** [comment]
Default params are not part of the R7RS standard AFAIK. And I can't find SRFI that will implement something like this. Except [SRFI 227: Optional Arguments](https://srfi.schemers.org/srfi-227/srfi-227.html), but the syntax is different.

You could use the R7RS implementation that is provided but I'm not sure if it will work, it requires a `syntax-case` macro. There is [R7RS implementation](https://github.com/scheme-requests-for-implementation/srfi-227) but it will require heavy refactoring to make it work. Part of the code (like every SRFI) requires R7RS libraries that are not yet supported.

You can try to refactor the code and put everything that is needed into one file and test if it works, but I don't guarantee that it will.

**Comment by dragoncoder047** [comment]
Just looked at SRFI 227 and noticed: my `(lambda*)` is equivalent to the SRFI's `(opt*-lambda)` and `(define*)` to `(define-optionals*)`. Niiiiice.
