### ISSUE TITLE
Detect when standard library bootstrap is fully loaded

### ISSUE THREAD

**Issue by dragoncoder047** [jcubic/lips#250]
Been playing around with embedding LIPS in an application. I am using the latest bleeding edge version from devel branch.

```html
<script src="https://cdn.jsdelivr.net/gh/jcubic/lips@07197424de02f22a2a642bd666e5a5f250a648e9/dist/lips.min.js"
            bootstrap></script>
```

When the application starts up it fetches and runs its own startup file using `lips.exec()`.

Sometimes I get the error ``Error: Unbound variable `number->string'`` when the startup script runs, and sometimes I don't. I traced this to the fact that the standard library may or may not be loaded when the startup script runs.

So I would like to delay the startup script to until LIPS has bootstrapped itself. Is there a promise hook I can wait on to do this?

**Comment by jcubic** [comment]
Thanks for the report, I will look into that.

**Comment by jcubic** [comment]
I just checked and this should never happen, since everything in LIPS is async and boostrap execute `(load)` of main file and next script only executes when load finishes.

Can you create an example of the code that fails and throws an error?

**Comment by dragoncoder047** [comment]
Here's an example (and a possible solution):
```html
<script src="https://cdn.jsdelivr.net/gh/jcubic/lips@07197424de02f22a2a642bd666e5a5f250a648e9/dist/lips.min.js"
            bootstrap></script>
```
```js
async function waitForLIPS() {
  if (lips.env.get("force", { throwError: false }) == undefined) {
    await lips.bootstrap();
  }
}

async function main() {
  //await waitForLIPS();
  await lips.exec("(display (number->string (** 10 100))) (flush-output)");
}
main().catch((e) => console.error(e.stack));
```

Tested in codepen. It prints the same error I got. But if you uncomment the `waitForLIPS()` code, it works (prints 10^100, as expected).

---

(Regarding my particular use case: The `lips.exec()` call was being triggered from an A-Frame component init function, which is also supposed to be async, but there must be a race condition.)

**Comment by jcubic** [comment]
Oh so you're using JavaScript to run Scheme. In that case you can run lips.bootstrap() yourself.

```javascript
lips.bootstrap().then(() => {
   /* your code */
});
```

The main purpose of bootstrap argument is to use only Scheme in your HTML, my first code required to bootstrap manually.

```html
<script src="https://cdn.jsdelivr.net/gh/jcubic/lips@07197424de02f22a2a642bd666e5a5f250a648e9/dist/lips.min.js"
            bootstrap></script>
<script type="text/x-scheme">
(display (number->string (** 10 100)))
</script>
```

**Comment by dragoncoder047** [comment]
> Oh so you're using JavaScript to run Scheme. In that case you can run lips.bootstrap() yourself.

Ah. I thought that you needed the bootstrap attribute to do the bootstrapping in the first place anyway before you run any Scheme by any method. Good to know!
