### ISSUE TITLE
You can't append to an empty list

### ISSUE THREAD

**Issue by jcubic** [jcubic/lips#311]
This is a huge mistake on my end. Now when an empty list is an instance of nil you can't append to an empty list:

```scheme
(let ((x ()))
  (append! x (list 10) (list 20))
  (print x))
```

This prints an empty list. There is a bug in the `append!` implementation but after fixing it you still can't append to an empty list.

We need to get rid of nil somehow and create an empty list differently than the early implementation of `(undefined . undefined)`.

**Comment by jcubic** [comment]
This will be a breaking change since nil constant needs to be removed from the library and each time when `()` appears it needs to create a Pair with a marker that it's an empty list.

in 58bc087974452f4dd778af84d5486fe395212b4b all comparisons to nil were replaced with the `is_nil()` function so it will be easier to remove nil.

Also `lips.nil` needs to be removed since it will not longer be a single value.

**Comment by lassik** [comment]
I didn't examine the details, but it sounds like you are going to do something unusual and perhaps unnecessarily complicated.

For example, see the definition of [`append!` in SRFI 1](https://srfi.schemers.org/srfi-1/srfi-1.html#append!):

> `append!` is the "linear-update" variant of `append` -- it is allowed, but not required, to alter cons cells in the argument lists to construct the result list.

So `(define append! append)` is one valid definition.

Traditionally, in both Lisp and Scheme, `(append! foo bar)` is never guaranteed to modify `foo`. What coders must use insted is `(set! foo (append! foo bar))`. To guarantee that `foo` is modified, `append!` would have to be a macro.

**Comment by jcubic** [comment]
@lassik thanks for the explanation. That would simplify the code.

I'm closing as not an issue.
