### ISSUE TITLE
Remove nil parser constant

### ISSUE THREAD

**Issue by jcubic** [jcubic/lips#332]
Right now:

```scheme
(symbol? 'nil)
;; ==> #f
```

According to R7RS, there should be no `nil` like in other lisps.

**Comment by lassik** [comment]
In Common Lisp (e.g. SBCL or GNU CLISP) `nil` is **both** a symbol **and** a list. This is traditional in Lisp.

```
(symbolp nil)  => t
(symbolp 'nil) => t
(listp nil)    => t
(eq nil 'nil)  => t
(eq nil '())   => t
```

**Comment by jcubic** [comment]
I have no idea how I would be able to make this work in LIPS. But just removing it, is ok. User will be able to use nil as a variable name. And if he wants `nil` he can use JavaScript `lips.nil` that is still there or use `(define nil ())`.
