### ISSUE TITLE
Check grammar mistakes in documntation

### ISSUE THREAD

**Issue by jcubic** [jcubic/lips#395]
I was just checking the documentation:

https://lips.js.org/docs/scheme-intro/input-output

And found few examples of missing "a" and "an" before nouns.

The task is to real whole documentation and correct any grammar (including above) that you can find.

**Comment by ArshadAriff** [comment]
Can i work on this @jcubic sir?

**Comment by jcubic** [comment]
@ArshadAriff yes, but note that there are probably not a lot of grammar mistakes because I used language tool when writing docs. But it seems that there are still small issues.
