### ISSUE TITLE
accurate position of syntax error when parsing

### ISSUE THREAD

**Issue by dragoncoder047** [jcubic/lips#416]
When I call lips.parse() and it gives me a syntax error there seems to be no way to see at what position in the source the parse error occurred, cause the comments and whitespace get thrown out.

<img width="508" alt="Screenshot 2024-12-09 at 11 13 47 AM" src="https://github.com/user-attachments/assets/51936b92-68c7-4e64-80f0-a0ed6a1b0306">

I also tried the "parse with metadata" option you shared earlier in https://github.com/LIPS-scheme/lips/issues/414#issuecomment-2523399475, but it gave the same result (no `__line__` or `__col__` appeared).

is there a better way to find the exact index of a syntax error?

**Comment by jcubic** [comment]
It may not be as simple as adding the metadata.

**Comment by jcubic** [comment]
Actually, I just checked, and all parse errors came from the parser that have info about the line and col. I will see if I can add this information to the error when `meta` is used.

**Comment by jcubic** [comment]
Added the same metadata to the parse errors.

**Comment by dragoncoder047** [comment]
Hmmm. I updated my html files to point to `https://cdn.jsdelivr.net/gh/LIPS-scheme/lips@b372c7e4f6a1963788192612e34170a56976dca4/dist/lips.js` which is this plus the #417 fix, and am using this function to parse

```js
/**
 * @param {string} source
 * @returns {Promise<lips.Pair[]>}
 */
export async function parseWithMetadata(source) {
    const parser = new lips.Parser({ env: lips.env, meta: true });
    parser.prepare(source);
    return await lips.parse(parser);
}
```

but am not getting `__line__` and `__col__` on the errors thrown. Must be a browser caching problem, will update later...

**Comment by jcubic** [comment]
It works, I've put your code into CodPen: https://codepen.io/jcubic/pen/MYgexza?editors=0012

**Comment by dragoncoder047** [comment]
Now that I've force-reloaded many times, the cache has cleared and I am getting line/columns on some of the syntax errors now.

However I am still not getting position info for the "Parser: expected parenthesis but eof found" error. Indeed, when you open the codepen you shared above and change the ")" to "(", the position information all shows up, but is all undefined.

**Comment by jcubic** [comment]
The problem was that lexer was returning `eof` object instead of token with metadata, when it reach the end of the input. But the last token is still accessible from `parser.__lexer__.__token__`.

**Comment by jcubic** [comment]
Added line number to all error messages, when using higher level `lips.Interpreter` interface.

**Comment by jcubic** [comment]
Closing as solved
