### ISSUE TITLE
Replace all **NOTE** in documentation

### ISSUE THREAD

**Issue by jcubic** [jcubic/lips#420]
Replace all `**NOTE**` by `:::info` block in documentation

See: d648cef8425a8cdb08aa567aeafc164bd7eadbad as a reference.

Run:

```bash
$ git grep '\*\*NOTE\*\*'
```

to see all instances.

**Comment by spudoodle** [comment]
Hey, I would like to work on this

**Comment by jcubic** [comment]
Sure, go ahead.

**Comment by spudoodle** [comment]
Hey @jcubic, should I handle the `NOTE` section on the landing screen?

**Comment by jcubic** [comment]
No, the change will only work in markdown files.
